---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - /env/common.env
    environment:
      - URL=treehausmedia.com
      - SUBDOMAINS=www,admin,
      - VALIDATION=http
      - EMAIL=meanoldtreelv@gmail.com
    volumes:
      - /docker/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - /env/common.env
    volumes:
      - /docker/jellyfin:/config
      - /docker/library:/data/library
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped


networks:
  default:
    name: SWAG
    external: true
