---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - /env/common.env
    environment:
      - URL=treehausmedia.com
      - SUBDOMAINS=www,admin,watch
      - VALIDATION=http
      - EMAIL=meanoldtreelv@gmail.com
    volumes:
      - /docker/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - /env/common.env
    volumes:
      - /docker/jellyfin:/config
      - /docker/library:/data/library
      - /docker/googledrive:/googledrive:ro
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    env_file:
      - /env/common.env
    environment:
      - NZBGET_USER=nzbget #optional
      - NZBGET_PASS=Valoren89 #optional
    volumes:
      - /docker/nzbget:/config
      - /docker/library/downloads:/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped
 
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - /env/common.env
    volumes:
      - /docker/sonarr:/config
      - /docker/library:/tv #optional
      - /docker/library/downloads:/downloads #optional
      - /docker/googledrive:/googledrive:ro
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - /env/common.env
    volumes:
      - /docker/radarr:/config
      - /docker/library/movies:/movies #optional
      - /docker/library/downloads:/downloads #optional
      - /docker/googledrive:/googledrive:ro
    ports:
      - 7878:7878
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    env_file:
      - /env/common.env
    volumes:
      - /docker/deluge:/config
      - /docker/library/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


networks:
  default:
    name: SWAG
    external: true
